config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :guides, only: [:index], defaults: { format: 'json' }

  root to: 'dashboard#show'
  match '/flights', to: 'flights#destination', via: [:get, :post]
  # post '/flights', to: 'flights#destination'
  get 'flights/random_destination'
end

app/models/guide.rb
class Guide < User
  include Gravtastic

  gravtastic d: 'identicon', s: 100
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/tourist.rb
class Tourist < User
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :address

  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(
        %i(type email password password_confirmation name address)
      )
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def destination
    options = {:query=>{
      :origin        => params[:origin],
      :destination   => params[:destination],
      :departuredate => params[:departuredate],
      :returndate    => params[:returndate]
    }
    }
    if options[:query][:origin] != nil

      @flights = SabreDevStudio::Base.get('/v1/shop/flights', options)["PricedItineraries"]
      # @flights = @flights['PricedItineraries']
    end
    # render json: @flights.to_json
    # require "pry"; binding.pry
 
  end

  def random_destination
    # options = {
    #   :origin        => params[:origin],
    #   :departuredate => params[:departure_date],
    #   :returndate    => params[:return_date],
    #   :theme         => params[:theme]
    # }

    options = {:query=>{
      :origin        => 'JFK',
      :departuredate => '2014-10-01',
      :returndate    => '2014-10-15',
      :theme         => 'BEACH'
      } 
    }
    @flights = SabreDevStudio::Base.get('/v1/shop/flights/fares',options)
    render json: @flights.to_json
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    guides = Guide.near(params[:location])

    render json: guides.to_json(methods: [:gravatar_url])
  end
end

app/controllers/traitify_controller.rb
class TraitifyController < ApplicationController
  def index
    @tratify = Traitify.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper

end

app/views/dashboard/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form action="<%= guides_path %>" class="search-form">
      <div class="input-group">
        <input type="text" name="location" placeholder="enter location" class="form-control input-lg">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-primary btn-lg">
            Search
          </button>
        </span>
      </div>
    </form>
  </div>
</div>

<br/>
<br/>

<div class="row">
  <div class="col-md-8">
    <div class="search-map" style="width: 100%; height: 500px;">
    </div>
  </div>

  <div class="col-md-4">
    <div class="search-results">
      No results yet.
    </div>
  </div>
</div>

<div class="assessment-box">
  <div class="assessment"></div>
</div>

app/views/flights/destination.html.erb
<div class="container">
  <div class="col-md-5">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Search for Flights</h3>
      </div>
      <div class="panel-body">

        <%= form_tag ( '/flights') do %>
        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">FROM</label>
          <div class="col-lg-10">
            <%= text_field_tag "origin", "", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">TO</label>
          <div class="col-lg-10">
            <%= text_field_tag "destination", "", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">Flying Date</label>
          <div class="col-lg-10">
            <%= text_field_tag "departuredate", "", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label for="inputEmail" class="col-lg-2 control-label">Return Date</label>
          <div class="col-lg-10">
            <%= text_field_tag "returndate", "", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <!-- <input value="submit" type="submit" id ="flights" class="btn btn-primary"> -->
            <%= submit_tag "Submit", :class=> "btn btn-md btn-primary" %>
          </div>
        </div>

        <% end %>

      </div>
    </div>

  </div>


  <div class="col-md-6">
    <% if @flights %>
      <% @flights.each do |flight| %>
        <p>Flight: <%= flight["AirItineraryPricingInfo"]["ItinTotalFare"]["TotalFare"]["Amount"] %>USD</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= notice %>.</strong>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><%= alert %></strong>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntegratedTours</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="http://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/flatly/bootstrap.min.css" rel="stylesheet">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "partials/navigation" %>
    <%= render "layouts/flash_messages" %>

    <%= yield %>

    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?v=3.exp' %>

<br><br><br>
    <center>
      <footer>
        <%= link_to "https://github.com/dahal/IntegratedTours" do %>
          <i class="fa fa-github"></i>
          Integrated Tours
        <% end %>
      </footer>
    </center>

  </body>
</html>

app/views/layouts/guide_profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntegratedTours</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="continer">

    <%= render "refills/small_nav" %>

    <section class="left-25">
      <div class="gravatar">Gravatar Pic</div>
      <div class="traitify-info">Traitify Info</div>
      <div class="contact-info">Contact Info</div>
    </section>
    <section class="right-75">
      <article class="bio">Bio Information Here</article>
      <div class="inbox">Inbox to be done here</div>
    </section>
  </div>
</body>
</html>

app/views/partials/_navigation.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <span class="fa fa-globe"></span>
      ToooR
    </a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      </li>
      <% else %>
      <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
      <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/refills/_navigation.html.erb
<header class="navigation">
  <div class="menu-wrapper">
    <a href="javascript:void(0)" class="logo">
      <img src="https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png" alt="">
    </a>
    <p class="navigation-menu-button" id="js-mobile-menu">MENU</p>
    <div class="nav">
      <ul id="navigation-menu">
        <li class="nav-link"><a href="javascript:void(0)">Products</a></li>
        <li class="nav-link"><a href="javascript:void(0)">About Us</a></li>
        <li class="nav-link"><a href="javascript:void(0)">Contact</a></li>
        <li class="nav-link more"><a href="javascript:void(0)">More</a>
          <ul class="submenu">
            <li><a href="javascript:void(0)">Submenu Item</a></li>
            <li><a href="javascript:void(0)">Another Item</a></li>
          </ul>
        </li>
        
      </ul>
    </div>
    <div class="navigation-tools">
      <div class="search-bar">
        <div class="search-and-submit">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/Magnus-G/Random/master/search-icon.png" alt="">
          </button>
        </div>
      </div>
      <a href="javascript:void(0)" class="sign-up">Sign Up</a>
    </div>
  </div>
</header>